# Generated by Django 4.2.11 on 2026-02-05 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
